<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CommunityOS.Organization.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommunityOS.Organization.Application\CommunityOS.Organization.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\CommunityOS.Infrastructure.Common\CommunityOS.Infrastructure.Common.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\CommunityOS.EventBus\CommunityOS.EventBus.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>