// <auto-generated />
using System;
using CommunityOS.Knowledge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityOS.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    partial class KnowledgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("knowledge")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.AiSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_id");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_on");

                    b.Property<int>("ReviewState")
                        .HasColumnType("integer")
                        .HasColumnName("review_state");

                    b.Property<DateTime?>("ReviewedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_on");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("ai_suggestions", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ModelId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("answers", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("categories", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Discussion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("discussions", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("EditionYear")
                        .HasColumnType("integer")
                        .HasColumnName("edition_year");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<string>("Publisher")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("publisher");

                    b.Property<string>("Translator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("translator");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("editions", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.OrganizationUnitReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSeenOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unit_type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_unit_references_organization_id");

                    b.ToTable("organization_unit_references", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Passage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("ReferencePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference_path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("passages", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_answer_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid?>("MergedOntoQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_onto_question_id");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("questions", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.Property<Guid>("PassageId")
                        .HasColumnType("uuid")
                        .HasColumnName("passage_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PassageId");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("references", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("topics", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_language");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("original_language");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("work_type");

                    b.HasKey("Id");

                    b.ToTable("works", "knowledge");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Answer", b =>
                {
                    b.OwnsMany("CommunityOS.Knowledge.Domain.Entities.AnswerRevision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body");

                            b1.Property<DateTime>("RevisedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revised_on");

                            b1.Property<int>("Revision")
                                .HasColumnType("integer")
                                .HasColumnName("revision");

                            b1.Property<Guid>("answer_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("answer_id");

                            b1.ToTable("answer_revisions", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("answer_id");
                        });

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Discussion", b =>
                {
                    b.OwnsMany("CommunityOS.Knowledge.Domain.Entities.Comment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid")
                                .HasColumnName("author_id");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("body");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on");

                            b1.Property<Guid>("discussion_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("discussion_id");

                            b1.ToTable("comments", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("discussion_id");
                        });

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Passage", b =>
                {
                    b.OwnsMany("CommunityOS.Knowledge.Domain.Entities.PassageRevision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CorrectedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("corrected_on");

                            b1.Property<int>("Revision")
                                .HasColumnType("integer")
                                .HasColumnName("revision");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text");

                            b1.Property<Guid>("passage_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("passage_id");

                            b1.ToTable("passage_revisions", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("passage_id");
                        });

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("CommunityOS.Knowledge.Domain.Aggregates.Question", b =>
                {
                    b.OwnsMany("CommunityOS.Knowledge.Domain.Entities.ModerationFlag", "ModerationFlags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("FlaggedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("flagged_by");

                            b1.Property<DateTime>("FlaggedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("flagged_on");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("question_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("question_id");

                            b1.ToTable("moderation_flags", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("question_id");
                        });

                    b.OwnsMany("CommunityOS.Knowledge.Domain.Entities.QuestionLifecycleEvent", "LifecycleEvents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("actor_id");

                            b1.Property<string>("FromStatus")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("from_status");

                            b1.Property<DateTime>("OccurredOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_on");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("to_status");

                            b1.Property<Guid>("question_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("question_id");

                            b1.ToTable("question_lifecycle_events", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("question_id");
                        });

                    b.OwnsMany("CommunityOS.Knowledge.Domain.Entities.QuestionTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.Property<Guid>("question_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("question_id");

                            b1.ToTable("tags", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("question_id");
                        });

                    b.Navigation("LifecycleEvents");

                    b.Navigation("ModerationFlags");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
