// <auto-generated />
using System;
using CommunityOS.Organization.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityOS.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260811235852_InitialCreateOrganization")]
    partial class InitialCreateOrganization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("appointment_type");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_on");

                    b.Property<Guid?>("EndedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by");

                    b.Property<DateTime?>("EndedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_on");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId", "OrganizationUnitId", "AppointmentType");

                    b.ToTable("appointments", "organization");
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.Committee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommitteeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("committee_type");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("committees", "organization");
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.DelegationFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DelegateId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegate_id");

                    b.Property<string>("DelegationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("delegation_type");

                    b.Property<Guid>("DelegatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegator_id");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<DateTime>("GrantedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_on");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_on");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DelegateId");

                    b.HasIndex("DelegatorId");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("delegation_facts", "organization");
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("EstablishedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("established_on");

                    b.Property<string>("InstitutionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("institution_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("institutions", "organization");
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DissolvedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dissolved_on");

                    b.Property<DateTime?>("EstablishedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("established_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("organizations", "organization");
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unit_type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("organization_units", "organization");
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.Appointment", b =>
                {
                    b.OwnsOne("CommunityOS.Organization.Domain.ValueObjects.EffectivePeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EffectiveFrom")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("effective_from");

                            b1.Property<DateTime?>("EffectiveUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("effective_until");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("appointments", "organization");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.Committee", b =>
                {
                    b.OwnsOne("CommunityOS.Organization.Domain.ValueObjects.Jurisdiction", "Jurisdiction", b1 =>
                        {
                            b1.Property<Guid>("CommitteeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ScopeId")
                                .HasColumnType("uuid")
                                .HasColumnName("jurisdiction_scope_id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("jurisdiction_type");

                            b1.HasKey("CommitteeId");

                            b1.ToTable("committees", "organization");

                            b1.WithOwner()
                                .HasForeignKey("CommitteeId");
                        });

                    b.OwnsMany("CommunityOS.Organization.Domain.Entities.CommitteeMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("person_id");

                            b1.Property<string>("RoleCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("role_code");

                            b1.Property<Guid>("committee_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PersonId");

                            b1.HasIndex("committee_id");

                            b1.ToTable("committee_members", "organization");

                            b1.WithOwner()
                                .HasForeignKey("committee_id");

                            b1.OwnsOne("CommunityOS.Organization.Domain.ValueObjects.EffectivePeriod", "Period", b2 =>
                                {
                                    b2.Property<Guid>("CommitteeMemberId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("EffectiveFrom")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("effective_from");

                                    b2.Property<DateTime?>("EffectiveUntil")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("effective_until");

                                    b2.HasKey("CommitteeMemberId");

                                    b2.ToTable("committee_members", "organization");

                                    b2.WithOwner()
                                        .HasForeignKey("CommitteeMemberId");
                                });

                            b1.Navigation("Period")
                                .IsRequired();
                        });

                    b.Navigation("Jurisdiction")
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.DelegationFact", b =>
                {
                    b.OwnsOne("CommunityOS.Organization.Domain.ValueObjects.EffectivePeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("DelegationFactId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EffectiveFrom")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("effective_from");

                            b1.Property<DateTime?>("EffectiveUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("effective_until");

                            b1.HasKey("DelegationFactId");

                            b1.ToTable("delegation_facts", "organization");

                            b1.WithOwner()
                                .HasForeignKey("DelegationFactId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.Institution", b =>
                {
                    b.OwnsOne("CommunityOS.Organization.Domain.ValueObjects.Jurisdiction", "Jurisdiction", b1 =>
                        {
                            b1.Property<Guid>("InstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ScopeId")
                                .HasColumnType("uuid")
                                .HasColumnName("jurisdiction_scope_id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("jurisdiction_type");

                            b1.HasKey("InstitutionId");

                            b1.ToTable("institutions", "organization");

                            b1.WithOwner()
                                .HasForeignKey("InstitutionId");
                        });

                    b.Navigation("Jurisdiction")
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.Organization", b =>
                {
                    b.OwnsOne("CommunityOS.Organization.Domain.ValueObjects.Jurisdiction", "Jurisdiction", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ScopeId")
                                .HasColumnType("uuid")
                                .HasColumnName("jurisdiction_scope_id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("jurisdiction_type");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organizations", "organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Jurisdiction")
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Organization.Domain.Aggregates.OrganizationUnit", b =>
                {
                    b.OwnsMany("CommunityOS.Organization.Domain.Entities.OrganizationUnitParent", "Parents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ParentId")
                                .HasColumnType("uuid")
                                .HasColumnName("parent_id");

                            b1.Property<Guid>("unit_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ParentId");

                            b1.HasIndex("unit_id");

                            b1.ToTable("organization_unit_parents", "organization");

                            b1.WithOwner()
                                .HasForeignKey("unit_id");

                            b1.OwnsOne("CommunityOS.Organization.Domain.ValueObjects.EffectivePeriod", "Period", b2 =>
                                {
                                    b2.Property<Guid>("OrganizationUnitParentId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("EffectiveFrom")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("effective_from");

                                    b2.Property<DateTime?>("EffectiveUntil")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("effective_until");

                                    b2.HasKey("OrganizationUnitParentId");

                                    b2.ToTable("organization_unit_parents", "organization");

                                    b2.WithOwner()
                                        .HasForeignKey("OrganizationUnitParentId");
                                });

                            b1.Navigation("Period")
                                .IsRequired();
                        });

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
