// <auto-generated />
using System;
using CommunityOS.Correspondence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityOS.Persistence.Migrations
{
    [DbContext(typeof(CorrespondenceDbContext))]
    partial class CorrespondenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("correspondence")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.ExportActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FilterSummary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("filter_summary");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("format");

                    b.Property<bool>("IncludedSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("included_sensitive");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_on");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.HasKey("Id");

                    b.HasIndex("RequestedOn")
                        .HasDatabaseName("ix_export_activity_requested_on");

                    b.ToTable("export_activity", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.Letter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CancellationReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cancellation_reason_code");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_on");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_code");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeliveredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_on");

                    b.Property<string>("DeliveryFailureReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("delivery_failure_reason_code");

                    b.Property<DateTime?>("DispatchedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_on");

                    b.Property<string>("LastDispatchMethodCode")
                        .HasColumnType("text");

                    b.Property<int?>("LetterSequence")
                        .HasColumnType("integer")
                        .HasColumnName("letter_sequence");

                    b.Property<int?>("LetterYear")
                        .HasColumnType("integer")
                        .HasColumnName("letter_year");

                    b.Property<DateTime?>("MaterializedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("materialized_on");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid?>("RelatedLetterId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_letter_id");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("retention_class");

                    b.Property<DateTime?>("RetentionExpiresOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_expires_on");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sensitivity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<Guid?>("SubjectPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_person_id");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<DateTime?>("SubmittedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_on");

                    b.Property<string>("TemplateCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_code");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_letters_created_on");

                    b.HasIndex("OrganizationUnitId")
                        .HasDatabaseName("ix_letters_organization_unit_id");

                    b.HasIndex("RetentionClass", "RetentionExpiresOn")
                        .HasDatabaseName("ix_letters_retention_expiry")
                        .HasFilter("retention_expires_on IS NOT NULL");

                    b.HasIndex("Status", "SubmittedOn")
                        .HasDatabaseName("ix_letters_status_submitted_on");

                    b.HasIndex("OrganizationUnitId", "LetterYear", "LetterSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_letters_unit_year_sequence")
                        .HasFilter("letter_year IS NOT NULL AND letter_sequence IS NOT NULL");

                    b.ToTable("letters", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_on");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid")
                        .HasColumnName("letter_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_type");

                    b.HasKey("Id");

                    b.HasIndex("LetterId", "DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_letter_attachments_letter_document");

                    b.ToTable("letter_attachments", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterDeliveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid")
                        .HasColumnName("letter_id");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method_code");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.HasKey("Id");

                    b.HasIndex("LetterId")
                        .HasDatabaseName("ix_letter_delivery_records_letter_id");

                    b.ToTable("letter_delivery_records", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterDocumentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid")
                        .HasColumnName("letter_id");

                    b.Property<DateTime>("MaterializedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("materialized_on");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_letter_documents_document_id");

                    b.HasIndex("LetterId");

                    b.ToTable("letter_documents", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HoldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hold_type");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid")
                        .HasColumnName("letter_id");

                    b.Property<Guid>("PlacedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("placed_by");

                    b.Property<DateTime>("PlacedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_on");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.Property<Guid?>("ReleasedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("released_by");

                    b.Property<DateTime?>("ReleasedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_on");

                    b.HasKey("Id");

                    b.HasIndex("LetterId")
                        .HasDatabaseName("ix_letter_holds_active")
                        .HasFilter("released_on IS NULL");

                    b.ToTable("letter_holds", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_on");

                    b.Property<string>("DisplayLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_line");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid")
                        .HasColumnName("letter_id");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("LetterId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_letter_recipients_person_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_letter_recipients_unit_id");

                    b.ToTable("letter_recipients", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cause");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<Guid?>("LetterId")
                        .HasColumnType("uuid")
                        .HasColumnName("letter_id");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("LetterId")
                        .HasDatabaseName("ix_letter_status_history_letter_id");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("ix_letter_status_history_occurred_on");

                    b.ToTable("letter_status_history", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.OrganizationUnitReference", b =>
                {
                    b.Property<Guid>("OrganizationUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<DateTime?>("LastUpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_on");

                    b.Property<Guid?>("ParentOrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_organization_unit_id");

                    b.HasKey("OrganizationUnitId");

                    b.ToTable("organization_unit_references", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_template");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_template");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_templates_code");

                    b.ToTable("templates", "correspondence");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "correspondence");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "correspondence");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "correspondence");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterAttachment", b =>
                {
                    b.HasOne("CommunityOS.Correspondence.Domain.Letter", null)
                        .WithMany("Attachments")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterDeliveryRecord", b =>
                {
                    b.HasOne("CommunityOS.Correspondence.Domain.Letter", null)
                        .WithMany("DeliveryRecordsInternal")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterDocumentLink", b =>
                {
                    b.HasOne("CommunityOS.Correspondence.Domain.Letter", null)
                        .WithMany("DocumentLinks")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterHold", b =>
                {
                    b.HasOne("CommunityOS.Correspondence.Domain.Letter", null)
                        .WithMany()
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.LetterRecipient", b =>
                {
                    b.HasOne("CommunityOS.Correspondence.Domain.Letter", null)
                        .WithMany("Recipients")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("CommunityOS.Correspondence.Domain.Letter", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("DeliveryRecordsInternal");

                    b.Navigation("DocumentLinks");

                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
