<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Authorization\CommunityOS.Authorization.Application\CommunityOS.Authorization.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Records\CommunityOS.Records.API\CommunityOS.Records.API.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Records\CommunityOS.Records.Application\CommunityOS.Records.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Records\CommunityOS.Records.Domain\CommunityOS.Records.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Records\CommunityOS.Records.Infrastructure\CommunityOS.Records.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\src\Services\Records\CommunityOS.Records.API\appsettings.json"
          Link="Config\appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\src\Services\Records\CommunityOS.Records.API\appsettings.Production.json"
          Link="Config\appsettings.Production.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
</Project>