// <auto-generated />
using System;
using CommunityOS.Records.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityOS.Persistence.Migrations
{
    [DbContext(typeof(RecordsDbContext))]
    [Migration("20260819103859_AddRetentionRuleMaximumPeriod")]
    partial class AddRetentionRuleMaximumPeriod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("records")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityOS.Records.Domain.Aggregates.OrganizationUnitReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationUnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_records_organization_unit_references_unit_id");

                    b.ToTable("organization_unit_references", "records");
                });

            modelBuilder.Entity("CommunityOS.Records.Domain.Aggregates.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subject_type");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_on");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_records_current_version_id");

                    b.HasIndex("OrganizationUnitId")
                        .HasDatabaseName("ix_records_organization_unit_id");

                    b.ToTable("records", "records");
                });

            modelBuilder.Entity("CommunityOS.Records.Domain.Aggregates.RecordCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retired");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_record_categories_code");

                    b.ToTable("record_categories", "records");
                });

            modelBuilder.Entity("CommunityOS.Records.Domain.Aggregates.RetentionSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retired");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_retention_schedules_code");

                    b.ToTable("retention_schedules", "records");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "records");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "records");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "records");
                });

            modelBuilder.Entity("CommunityOS.Records.Domain.Aggregates.Record", b =>
                {
                    b.OwnsMany("CommunityOS.Records.Domain.Aggregates.RecordFieldValue", "WorkingFields", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("FieldKey")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("field_key");

                            b1.Property<string>("FieldValue")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)")
                                .HasColumnName("field_value");

                            b1.Property<bool>("IsSensitive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_sensitive");

                            b1.Property<Guid>("record_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("record_id");

                            b1.ToTable("record_working_fields", "records");

                            b1.WithOwner()
                                .HasForeignKey("record_id");
                        });

                    b.OwnsOne("CommunityOS.Records.Domain.Aggregates.RecordClassificationMetadata", "Classification", b1 =>
                        {
                            b1.Property<Guid>("record_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ClassificationCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("classification_code");

                            b1.Property<Guid?>("ClassifiedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("classified_by");

                            b1.Property<DateTime?>("ClassifiedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("classified_on");

                            b1.Property<bool>("IsSensitive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_sensitive");

                            b1.Property<DateTime?>("RetentionExpiredOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("retention_expired_on");

                            b1.Property<string>("RetentionScheduleCode")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("retention_schedule_code");

                            b1.HasKey("record_id");

                            b1.ToTable("record_classification", "records");

                            b1.WithOwner()
                                .HasForeignKey("record_id");
                        });

                    b.OwnsMany("CommunityOS.Records.Domain.Aggregates.RecordEvidenceReference", "Evidence", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AttachedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("attached_by");

                            b1.Property<DateTime>("AttachedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("attached_on");

                            b1.Property<DateTime?>("DocumentDeactivatedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("document_deactivated_on");

                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid")
                                .HasColumnName("document_id");

                            b1.Property<DateTime?>("DocumentRestoredOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("document_restored_on");

                            b1.Property<string>("ReferenceType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("reference_type");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("version_number");

                            b1.Property<Guid>("record_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("record_id", "DocumentId", "VersionNumber", "ReferenceType")
                                .IsUnique()
                                .HasDatabaseName("ix_record_evidence_document_version_type");

                            b1.ToTable("record_evidence_references", "records");

                            b1.WithOwner()
                                .HasForeignKey("record_id");
                        });

                    b.OwnsMany("CommunityOS.Records.Domain.Aggregates.RecordHold", "Holds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("HoldType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("hold_type");

                            b1.Property<Guid>("PlacedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("placed_by");

                            b1.Property<DateTime>("PlacedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("placed_on");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("reason");

                            b1.Property<Guid?>("ReleasedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("released_by");

                            b1.Property<DateTime?>("ReleasedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("released_on");

                            b1.Property<Guid>("record_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("record_id");

                            b1.ToTable("record_holds", "records");

                            b1.WithOwner()
                                .HasForeignKey("record_id");

                            b1.OwnsMany("CommunityOS.Records.Domain.Aggregates.RecordHoldDocumentReference", "DocumentReferences", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("DocumentId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("document_id");

                                    b2.Property<int?>("VersionNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("version_number");

                                    b2.Property<Guid>("record_hold_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("record_hold_id");

                                    b2.ToTable("record_hold_document_references", "records");

                                    b2.WithOwner()
                                        .HasForeignKey("record_hold_id");
                                });

                            b1.Navigation("DocumentReferences");
                        });

                    b.OwnsMany("CommunityOS.Records.Domain.Aggregates.RecordOrganizationScope", "Scopes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OrganizationUnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("organization_unit_id");

                            b1.Property<Guid>("record_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("record_id", "OrganizationUnitId")
                                .IsUnique()
                                .HasDatabaseName("ix_record_scopes_record_organization_unit");

                            b1.ToTable("record_scopes", "records");

                            b1.WithOwner()
                                .HasForeignKey("record_id");
                        });

                    b.OwnsMany("CommunityOS.Records.Domain.Aggregates.RecordVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AppliedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("applied_by");

                            b1.Property<DateTime>("AppliedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("applied_on");

                            b1.Property<string>("ChangeReason")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("change_reason");

                            b1.Property<int?>("SupersedesVersionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("supersedes_version_number");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("version_number");

                            b1.Property<Guid>("record_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("record_id", "VersionNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_record_versions_record_version_number");

                            b1.ToTable("record_versions", "records");

                            b1.WithOwner()
                                .HasForeignKey("record_id");

                            b1.OwnsMany("CommunityOS.Records.Domain.Aggregates.RecordFieldValue", "Fields", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FieldKey")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("field_key");

                                    b2.Property<string>("FieldValue")
                                        .IsRequired()
                                        .HasMaxLength(8000)
                                        .HasColumnType("character varying(8000)")
                                        .HasColumnName("field_value");

                                    b2.Property<bool>("IsSensitive")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_sensitive");

                                    b2.Property<Guid>("record_version_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("record_version_id");

                                    b2.ToTable("record_field_values", "records");

                                    b2.WithOwner()
                                        .HasForeignKey("record_version_id");
                                });

                            b1.Navigation("Fields");
                        });

                    b.Navigation("Classification")
                        .IsRequired();

                    b.Navigation("Evidence");

                    b.Navigation("Holds");

                    b.Navigation("Scopes");

                    b.Navigation("Versions");

                    b.Navigation("WorkingFields");
                });

            modelBuilder.Entity("CommunityOS.Records.Domain.Aggregates.RetentionSchedule", b =>
                {
                    b.OwnsMany("CommunityOS.Records.Domain.Aggregates.RetentionRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("category");

                            b1.Property<string>("Disposition")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("disposition");

                            b1.Property<string>("MaximumPeriod")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("maximum_period");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("note");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("period");

                            b1.Property<string>("StartTrigger")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("start_trigger");

                            b1.Property<Guid>("retention_schedule_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("retention_schedule_id");

                            b1.ToTable("retention_rules", "records");

                            b1.WithOwner()
                                .HasForeignKey("retention_schedule_id");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
