using CommunityOS.AI.Domain;
using CommunityOS.AI.Domain.Exceptions;
using Microsoft.Extensions.Logging;

namespace CommunityOS.AI.Infrastructure;

/// <summary>
/// Safety enforcer that validates input before inference and output after inference.
/// ADR-030 decision 14: no content generated by providers is authoritative.
/// </summary>
internal sealed class AiSafetyEnforcer
{
    private readonly ILogger<AiSafetyEnforcer> _logger;

    public AiSafetyEnforcer(ILogger<AiSafetyEnforcer> logger)
    {
        _logger = logger;
    }

    public void ValidateBeforeInference(AiInferenceRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Input))
        {
            _logger.InputValidationFailed(request.SubjectId, request.Capability);

            throw new AiCapabilityNotSupportedException(request.Capability);
        }

        _logger.InputValidationPassed(request.SubjectId, request.Capability);
    }

    public void ValidateAfterInference(AiInferenceResponse response)
    {
        if (response.Outcome == "provider_disabled")
        {
            return;
        }

        _logger.OutputValidationPassed(response.Outcome);
    }
}

internal static partial class AiSafetyEnforcerLog
{
    [LoggerMessage(
        EventId = 0,
        Level = LogLevel.Debug,
        Message = "AI input validation passed: subject={SubjectId}, capability={Capability}")]
    public static partial void InputValidationPassed(this ILogger logger, Guid subjectId, string capability);

    [LoggerMessage(
        EventId = 1,
        Level = LogLevel.Warning,
        Message = "AI input validation failed: subject={SubjectId}, capability={Capability}, reason=empty_input")]
    public static partial void InputValidationFailed(this ILogger logger, Guid subjectId, string capability);

    [LoggerMessage(
        EventId = 2,
        Level = LogLevel.Debug,
        Message = "AI output validation passed: outcome={Outcome}")]
    public static partial void OutputValidationPassed(this ILogger logger, string outcome);
}
