<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CommunityOS.Identity.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommunityOS.Identity.Domain\CommunityOS.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\CommunityOS.Abstractions\CommunityOS.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\CommunityOS.Contracts\CommunityOS.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Mapster" />
  </ItemGroup>
</Project>
