<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CommunityOS.EventBus</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommunityOS.Abstractions\CommunityOS.Abstractions.csproj" />
    <ProjectReference Include="..\CommunityOS.Contracts\CommunityOS.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
