<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Authorization\CommunityOS.Authorization.Application\CommunityOS.Authorization.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Finance\CommunityOS.Finance.API\CommunityOS.Finance.API.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Finance\CommunityOS.Finance.Application\CommunityOS.Finance.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Finance\CommunityOS.Finance.Domain\CommunityOS.Finance.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Finance\CommunityOS.Finance.Infrastructure\CommunityOS.Finance.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\src\Services\Finance\CommunityOS.Finance.API\appsettings.json"
          Link="Config\appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\src\Services\Finance\CommunityOS.Finance.API\appsettings.Production.json"
          Link="Config\appsettings.Production.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
</Project>