<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Identity\CommunityOS.Identity.API\CommunityOS.Identity.API.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Identity\CommunityOS.Identity.Application\CommunityOS.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Identity\CommunityOS.Identity.Domain\CommunityOS.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Identity\CommunityOS.Identity.Infrastructure\CommunityOS.Identity.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
</Project>
