// <auto-generated />
using System;
using CommunityOS.Workflow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityOS.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260819161356_InitialCreateWorkflow")]
    partial class InitialCreateWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityOS.Workflow.Domain.Aggregates.OrganizationUnitReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationUnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_organization_unit_references_unit_id");

                    b.ToTable("organization_unit_references", "workflow");
                });

            modelBuilder.Entity("CommunityOS.Workflow.Domain.Aggregates.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("DomainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("domain_type");

                    b.Property<string>("DueIn")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("due_in");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_human_review");

                    b.Property<Guid?>("RetiredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("retired_by");

                    b.Property<DateTime?>("RetiredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_on");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_task_definitions_code");

                    b.ToTable("task_definitions", "workflow");
                });

            modelBuilder.Entity("CommunityOS.Workflow.Domain.Aggregates.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("DefinitionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("definition_code");

                    b.Property<Guid?>("DomainEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_entity_id");

                    b.Property<string>("DomainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("domain_type");

                    b.Property<DateTime?>("DueOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_on");

                    b.Property<Guid?>("EscalatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("escalated_by");

                    b.Property<DateTime?>("EscalatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_on");

                    b.Property<Guid?>("EscalatedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("escalated_to");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("escalation_reason");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid>("OriginatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("originator_id");

                    b.Property<string>("Outcome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("StartedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by");

                    b.Property<DateTime?>("StartedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionCode")
                        .HasDatabaseName("ix_workflow_tasks_definition_code");

                    b.HasIndex("DomainEntityId")
                        .HasDatabaseName("ix_workflow_tasks_domain_entity_id");

                    b.HasIndex("OrganizationUnitId")
                        .HasDatabaseName("ix_workflow_tasks_organization_unit_id");

                    b.HasIndex("DefinitionCode", "DomainType", "DomainEntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_tasks_open_definition_domain")
                        .HasFilter("\"status\" < 4 AND \"domain_entity_id\" IS NOT NULL");

                    b.ToTable("workflow_tasks", "workflow");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "workflow");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "workflow");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "workflow");
                });

            modelBuilder.Entity("CommunityOS.Workflow.Domain.Aggregates.TaskDefinition", b =>
                {
                    b.OwnsMany("CommunityOS.Workflow.Domain.Aggregates.TaskDefinitionOutcome", "PermittedOutcomes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("code");

                            b1.Property<Guid>("task_definition_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("task_definition_id", "Code")
                                .IsUnique()
                                .HasDatabaseName("ix_task_definition_outcomes_definition_code");

                            b1.ToTable("task_definition_outcomes", "workflow");

                            b1.WithOwner()
                                .HasForeignKey("task_definition_id");
                        });

                    b.Navigation("PermittedOutcomes");
                });

            modelBuilder.Entity("CommunityOS.Workflow.Domain.Aggregates.WorkflowTask", b =>
                {
                    b.OwnsMany("CommunityOS.Workflow.Domain.Aggregates.TaskActivity", "Activity", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("action");

                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("actor_id");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("notes");

                            b1.Property<DateTime>("OccurredOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_on");

                            b1.Property<string>("Outcome")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("outcome");

                            b1.Property<Guid>("task_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("task_id", "OccurredOn")
                                .HasDatabaseName("ix_task_activity_task_occurred_on");

                            b1.ToTable("task_activity", "workflow");

                            b1.WithOwner()
                                .HasForeignKey("task_id");
                        });

                    b.OwnsMany("CommunityOS.Workflow.Domain.Aggregates.TaskAssignment", "Assignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AssignedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("assigned_by");

                            b1.Property<DateTime>("AssignedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("assigned_on");

                            b1.Property<Guid>("task_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("task_id");

                            b1.ToTable("task_assignments", "workflow");

                            b1.WithOwner()
                                .HasForeignKey("task_id");

                            b1.OwnsMany("CommunityOS.Workflow.Domain.Aggregates.TaskAssignee", "Assignees", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("AssigneeId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("assignee_id");

                                    b2.Property<Guid>("task_assignment_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("task_assignment_id");

                                    b2.ToTable("task_assignment_assignees", "workflow");

                                    b2.WithOwner()
                                        .HasForeignKey("task_assignment_id");
                                });

                            b1.Navigation("Assignees");
                        });

                    b.OwnsMany("CommunityOS.Workflow.Domain.Aggregates.TaskScope", "Scopes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OrganizationUnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("organization_unit_id");

                            b1.Property<Guid>("task_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("task_id", "OrganizationUnitId")
                                .IsUnique()
                                .HasDatabaseName("ix_task_scopes_task_organization_unit");

                            b1.ToTable("task_scopes", "workflow");

                            b1.WithOwner()
                                .HasForeignKey("task_id");
                        });

                    b.Navigation("Activity");

                    b.Navigation("Assignments");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
