<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>CommunityOS.Events.API</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommunityOS.Events.Application\CommunityOS.Events.Application.csproj" />
    <ProjectReference Include="..\CommunityOS.Events.Infrastructure\CommunityOS.Events.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Asp.Versioning.Mvc" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="FluentValidation.AspNetCore" />
<PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
</Project>
