// <auto-generated />
using System;
using CommunityOS.Documents.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityOS.Persistence.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20260829033911_AddMassTransitOutbox")]
    partial class AddMassTransitOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documents")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityOS.Documents.Domain.Aggregates.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("owner_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationUnitId");

                    b.ToTable("documents", "documents");
                });

            modelBuilder.Entity("CommunityOS.Documents.Domain.Aggregates.OrganizationUnitReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSeenOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unit_type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_unit_references_organization_id");

                    b.ToTable("organization_unit_references", "documents");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "documents");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "documents");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "documents");
                });

            modelBuilder.Entity("CommunityOS.Documents.Domain.Aggregates.Document", b =>
                {
                    b.OwnsOne("CommunityOS.Documents.Domain.Aggregates.DocumentClassificationMetadata", "Classification", b1 =>
                        {
                            b1.Property<Guid>("document_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdministrativeHoldReference")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("administrative_hold_reference");

                            b1.Property<string>("ClassificationCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("classification_code");

                            b1.Property<Guid?>("ClassifiedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("classified_by");

                            b1.Property<DateTime?>("ClassifiedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("classified_on");

                            b1.Property<bool>("IsSensitive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_sensitive");

                            b1.Property<string>("LegalHoldReference")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("legal_hold_reference");

                            b1.Property<string>("RetentionCategory")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("retention_category");

                            b1.HasKey("document_id");

                            b1.ToTable("document_classification", "documents");

                            b1.WithOwner()
                                .HasForeignKey("document_id");
                        });

                    b.OwnsMany("CommunityOS.Documents.Domain.Aggregates.DocumentOrganizationScope", "Scopes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OrganizationUnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("organization_unit_id");

                            b1.Property<Guid>("document_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("document_id", "OrganizationUnitId")
                                .IsUnique()
                                .HasDatabaseName("ix_document_scopes_document_organization_unit");

                            b1.ToTable("document_scopes", "documents");

                            b1.WithOwner()
                                .HasForeignKey("document_id");
                        });

                    b.OwnsMany("CommunityOS.Documents.Domain.Aggregates.DocumentReference", "References", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on");

                            b1.Property<string>("ReferenceType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("reference_type");

                            b1.Property<string>("SourceContext")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_context");

                            b1.Property<Guid>("SourceEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_entity_id");

                            b1.Property<Guid>("document_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("document_id", "SourceContext", "SourceEntityId", "ReferenceType")
                                .IsUnique()
                                .HasDatabaseName("ix_document_references_context_entity_type");

                            b1.ToTable("document_references", "documents");

                            b1.WithOwner()
                                .HasForeignKey("document_id");
                        });

                    b.OwnsMany("CommunityOS.Documents.Domain.Aggregates.DocumentVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("content_hash");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mime_type");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("object_key");

                            b1.Property<int>("ScanStatus")
                                .HasColumnType("integer")
                                .HasColumnName("scan_status");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("size_bytes");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("source");

                            b1.Property<Guid>("UploadedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("uploaded_by");

                            b1.Property<DateTime>("UploadedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_on");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("version_number");

                            b1.Property<Guid>("document_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("document_id", "VersionNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_document_versions_document_version_number");

                            b1.ToTable("document_versions", "documents");

                            b1.WithOwner()
                                .HasForeignKey("document_id");
                        });

                    b.Navigation("Classification")
                        .IsRequired();

                    b.Navigation("References");

                    b.Navigation("Scopes");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
