<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>CommunityOS.Community.API</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommunityOS.Community.Application\CommunityOS.Community.Application.csproj" />
    <ProjectReference Include="..\CommunityOS.Community.Infrastructure\CommunityOS.Community.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Asp.Versioning.Mvc" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="FluentValidation.AspNetCore" />
<PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
</Project>
