// <auto-generated />
using System;
using CommunityOS.Community.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityOS.Persistence.Migrations
{
    [DbContext(typeof(CommunityDbContext))]
    [Migration("20260812015141_InitialCreateCommunity")]
    partial class InitialCreateCommunity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("community")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityOS.Community.Domain.Aggregates.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("hierarchy_level");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("communities", "community");
                });

            modelBuilder.Entity("CommunityOS.Community.Domain.Aggregates.OrganizationReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JurisdictionScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("jurisdiction_scope_id");

                    b.Property<string>("JurisdictionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jurisdiction_type");

                    b.Property<DateTime>("LastSeenOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organization_type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("organization_references", "community");
                });

            modelBuilder.Entity("CommunityOS.Community.Domain.Aggregates.OrganizationUnitReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSeenOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unit_type");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_unit_references_organization_id");

                    b.ToTable("organization_unit_references", "community");
                });

            modelBuilder.Entity("CommunityOS.Community.Domain.Entities.Cluster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id");

                    b.ToTable("clusters", "community");
                });

            modelBuilder.Entity("CommunityOS.Community.Domain.Entities.LocalUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("community_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("community_id");

                    b.ToTable("local_units", "community");
                });

            modelBuilder.Entity("CommunityOS.Community.Domain.Aggregates.Community", b =>
                {
                    b.OwnsOne("CommunityOS.Community.Domain.ValueObjects.GeographicArea", "Area", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<string>("Region")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("region");

                            b1.HasKey("CommunityId");

                            b1.ToTable("communities", "community");

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.OwnsOne("CommunityOS.Community.Domain.ValueObjects.CommunityName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("CommunityId");

                            b1.ToTable("communities", "community");

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Community.Domain.Entities.Cluster", b =>
                {
                    b.OwnsOne("CommunityOS.Community.Domain.ValueObjects.GeographicArea", "Area", b1 =>
                        {
                            b1.Property<Guid>("ClusterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<string>("Region")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("region");

                            b1.HasKey("ClusterId");

                            b1.ToTable("clusters", "community");

                            b1.WithOwner()
                                .HasForeignKey("ClusterId");
                        });

                    b.OwnsOne("CommunityOS.Community.Domain.ValueObjects.CommunityName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ClusterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("ClusterId");

                            b1.ToTable("clusters", "community");

                            b1.WithOwner()
                                .HasForeignKey("ClusterId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Community.Domain.Entities.LocalUnit", b =>
                {
                    b.HasOne("CommunityOS.Community.Domain.Aggregates.Community", null)
                        .WithMany("LocalUnits")
                        .HasForeignKey("community_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CommunityOS.Community.Domain.ValueObjects.GeographicArea", "Area", b1 =>
                        {
                            b1.Property<Guid>("LocalUnitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<string>("Region")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("region");

                            b1.HasKey("LocalUnitId");

                            b1.ToTable("local_units", "community");

                            b1.WithOwner()
                                .HasForeignKey("LocalUnitId");
                        });

                    b.OwnsOne("CommunityOS.Community.Domain.ValueObjects.CommunityName", "Name", b1 =>
                        {
                            b1.Property<Guid>("LocalUnitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("LocalUnitId");

                            b1.ToTable("local_units", "community");

                            b1.WithOwner()
                                .HasForeignKey("LocalUnitId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("CommunityOS.Community.Domain.Aggregates.Community", b =>
                {
                    b.Navigation("LocalUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
