// <auto-generated />
using System;
using CommunityOS.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunityOS.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommunityOS.Identity.Domain.Aggregates.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on");

                    b.Property<DateTime>("LastUsedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_on");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<bool>("RefreshTokenUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("refresh_token_used");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_on");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family_id");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("TokenFamilyId");

                    b.HasIndex("UserAccountId", "RevokedOn");

                    b.ToTable("sessions", "identity");
                });

            modelBuilder.Entity("CommunityOS.Identity.Domain.Aggregates.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("DeactivatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTime?>("LastLoginOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_on");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("VerifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_on");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user_accounts", "identity");
                });

            modelBuilder.Entity("CommunityOS.Identity.Domain.Entities.RecoveryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime?>("ConsumedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_on");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_on");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "Purpose", "ExpiresOn");

                    b.ToTable("recovery_requests", "identity");
                });

            modelBuilder.Entity("CommunityOS.Identity.Domain.Entities.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "OccurredOn");

                    b.ToTable("security_events", "identity");
                });

            modelBuilder.Entity("CommunityOS.Identity.Domain.Aggregates.UserAccount", b =>
                {
                    b.OwnsMany("CommunityOS.Identity.Domain.Entities.Credential", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on");

                            b1.Property<DateTime?>("LastUsedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_used_on");

                            b1.Property<string>("Metadata")
                                .HasColumnType("text")
                                .HasColumnName("metadata");

                            b1.Property<string>("Secret")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("secret");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type_id");

                            b1.Property<Guid>("user_account_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("user_account_id");

                            b1.ToTable("user_account_credentials", "identity");

                            b1.WithOwner()
                                .HasForeignKey("user_account_id");
                        });

                    b.OwnsMany("CommunityOS.Identity.Domain.Entities.Device", "Devices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsTrusted")
                                .HasColumnType("boolean")
                                .HasColumnName("is_trusted");

                            b1.Property<DateTime?>("LastSeenOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_seen_on");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.Property<string>("Platform")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("platform");

                            b1.Property<DateTime>("RegisteredOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registered_on");

                            b1.Property<DateTime?>("TrustedUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("trusted_until");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("user_agent");

                            b1.Property<Guid>("user_account_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("user_account_id");

                            b1.ToTable("user_account_devices", "identity");

                            b1.WithOwner()
                                .HasForeignKey("user_account_id");
                        });

                    b.OwnsMany("CommunityOS.Identity.Domain.Entities.ExternalIdentity", "ExternalIdentities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("LinkedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("linked_on");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("provider");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("subject");

                            b1.Property<DateTime?>("UnlinkedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("unlinked_on");

                            b1.Property<Guid>("user_account_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("user_account_id");

                            b1.HasIndex("Provider", "Subject");

                            b1.ToTable("user_account_external_identities", "identity");

                            b1.WithOwner()
                                .HasForeignKey("user_account_id");
                        });

                    b.OwnsMany("CommunityOS.Identity.Domain.Entities.MfaMethod", "MfaMethods", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<string>("Secret")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("secret");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type_id");

                            b1.Property<DateTime?>("VerifiedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("verified_on");

                            b1.Property<Guid>("user_account_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("user_account_id");

                            b1.ToTable("user_account_mfa_methods", "identity");

                            b1.WithOwner()
                                .HasForeignKey("user_account_id");
                        });

                    b.Navigation("Credentials");

                    b.Navigation("Devices");

                    b.Navigation("ExternalIdentities");

                    b.Navigation("MfaMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
