<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Workflow\CommunityOS.Workflow.Application\CommunityOS.Workflow.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Workflow\CommunityOS.Workflow.Domain\CommunityOS.Workflow.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Workflow\CommunityOS.Workflow.Infrastructure\CommunityOS.Workflow.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
</Project>