<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Authorization\CommunityOS.Authorization.Application\CommunityOS.Authorization.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Notifications\CommunityOS.Notifications.API\CommunityOS.Notifications.API.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Notifications\CommunityOS.Notifications.Application\CommunityOS.Notifications.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Notifications\CommunityOS.Notifications.Domain\CommunityOS.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Notifications\CommunityOS.Notifications.Infrastructure\CommunityOS.Notifications.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\src\Services\Notifications\CommunityOS.Notifications.API\appsettings.json"
          Link="Config\appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\src\Services\Notifications\CommunityOS.Notifications.API\appsettings.Production.json"
          Link="Config\appsettings.Production.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
</Project>