using CommunityOS.SharedKernel.Domain.Primitives;

namespace CommunityOS.Knowledge.Domain.Enumerations;

/// <summary>
/// The provenance of an answer: authored by a community member or generated by
/// an AI model. AI answers always remain tied to an accepted AiSuggestion.
/// </summary>
public sealed class AnswerSource : Enumeration<int>
{
    public static readonly AnswerSource Member = new(1, "member");
    public static readonly AnswerSource Ai = new(2, "ai");

    private AnswerSource(int id, string name) : base(id, name) { }

    public static IEnumerable<AnswerSource> All => [Member, Ai];

    public static AnswerSource FromId(int id) =>
        All.FirstOrDefault(s => s.Id == id)
        ?? throw new ArgumentException($"Unknown AnswerSource id: {id}");

    public static AnswerSource FromName(string name) =>
        All.FirstOrDefault(s => string.Equals(s.Name, name, StringComparison.OrdinalIgnoreCase))
        ?? throw new ArgumentException($"Unknown AnswerSource name: {name}");
}