<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Authorization\CommunityOS.Authorization.Application\CommunityOS.Authorization.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Organization\CommunityOS.Organization.Application\CommunityOS.Organization.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Organization\CommunityOS.Organization.Domain\CommunityOS.Organization.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
</Project>
